### PR TITLE
Added maxWidth option

### PR DESCRIPTION
**Pull request by rafaelfaria**
Fixes issue #33

### CODE REVIEW

**Comment by alanmm** [comment]
can't find the maxWidth option on code.. was it removed?

when I put it to centered, it creates a 2-row wide strip, going beyond the boundaries of container.. is it supposed to be that way?

screenshot 2014-02-05 16 05 21

**Comment by rafaelfaria** [comment]
Hi alanmm, if you check the commits, I end up changing the name to "maxContainerWidth" which made more sense. But keep in mind you would have to check out my fork and not the original project.

I'm not sure what's going on with your project, I would have to have a look to debug it, but try using my fork and use the options maxContainerWidth combined with centered, and you might have some success on accomplishing what you want to do it.

Good luck.

**Comment by rafaelfaria** [comment]
This is the file I commited with this option:

https://github.com/rafaelfaria/Nested/blob/hotfix/max_width/jquery.nested.js

**Comment by alanmm** [comment]
Thanks for your help, @rafaelfaria! Now it's working!

**Pull request closed without merging**
