### PR TITLE
Added an option to receive methods

### PR DESCRIPTION
**Pull request by rafaelfaria**
Added Refresh method
Added Destroy method

Fixed issue #32

### CODE REVIEW

**Comment by andreas-pihlstrom** [comment]
Thanks for this!

**Comment by karland** [comment]
I am also looking for this function, but could not figure out how to use the added Refresh method. Could you give an example. That would be great. Thanks.

**Comment by rafaelfaria** [comment]
Hi karland. Try $("#el").nested("refresh") or $("#el").nested("destroy")

hope it helps!

**Comment by karland** [comment]
@rafaelfaria, thank you. Unfortunately it does not work. I created a button and wanted the refresh on a click event, but nothing happens. To see that the button is working I increased the size of the button and put a frame around my container. Both work fine. Only the refresh does not work at all. Any clues?

```
$('#MyButton').on('click', function() {
  $("#container").addClass('white-frame');
  $('#MyButton').addClass('large');
});
```

By the way, nested sits on a `#container`

```
 $(document).ready(function() { 
     $("#container").nested({...});
 });
```

**Pull request merged**
